/*
This Class is For Theater Model included
id for Generated by mongoDB id
theaterId for ID
seats for all seats id of this Theater
*/
package com.theaterapi.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotNull;
import java.util.List;

@Data
public class Theater {
    @Id
    private String id;
    @NotNull
    private String theaterId;
    private List<String> seats;

    public void setId(String id) {
        this.id = id;
    }

    public List<String> getSeats(){
        return this.seats;
    }
}
